# Generated by Django 6.0.3 on 2026-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
    ]
