# Generated by Django 6.0.3 on 2026-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_seed_service_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_text_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_text_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ar',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
