# Generated by Django 6.0.3 on 2026-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phone_whatsapp', models.CharField(max_length=20)),
                ('company_project_name', models.CharField(blank=True, max_length=150)),
                ('service_needed', models.CharField(max_length=120)),
                ('project_type', models.CharField(max_length=50)),
                ('existing_system', models.CharField(blank=True, max_length=10)),
                ('project_description', models.TextField()),
                ('problem_to_solve', models.TextField(blank=True)),
                ('main_goal', models.TextField(blank=True)),
                ('reference_links', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('expected_start_date', models.CharField(blank=True, max_length=60)),
                ('is_urgent', models.CharField(blank=True, max_length=10)),
                ('preferred_contact_method', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('project_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
